spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sweeties_db}
    username: ${DB_USER:sweeties_user}
    password: ${DB_PASS:secret}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    # You DON'T need to set url/user/pass again.
    # Flyway will automatically use the main spring.datasource.
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: ${ADMIN_USER:admin}
      password: ${ADMIN_PASSWORD:123456}
      roles: ${ADMIN_ROLES:ADMIN}

  mail:
    host: ${MAIL_HOST:smtp.infinitummail.com}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    default-encoding: UTF-8

sweeties:
  admin-email: ${ADMIN_EMAIL:sweeties_crochet@infinitummail.com}

application:
  name: sweeties

logging:
  level:
    org:
      springframework:
        web: DEBUG

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:change-me}
  expiration: ${JWT_EXPIRATION:86400000}

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME:dr6b4izzt}
  api_key: ${CLOUDINARY_API_KEY:764232222658472}
  api_secret: ${CLOUDINARY_API_SECRET:uetGVSOjLMXIP-jmnhCy3WNNL8s}
